NAME = a.out
SRC = And.c Mux.c Nand.c Nor.c Not.c Or.c Xor.c DMux.c Not16.c And16.c Or16.c Mux16.c Or8Way.c Mux4Way16.c Mux8way16.c DMux4Way.c DMux8Way.c HalfAdder.c FullAdder.c Add16.c Inc16.c ALU.c
all		:$(NAME)
$(NAME)	:$(SRC)
	gcc $(SRC) -o $(NAME)